### ISSUE TITLE
Problems of running pipelineMain.m

### ISSUE THREAD

**Issue by JasonAnn** [department-of-psychology/AFARtoolbox#2]
Hi! And thank you for making this code available. I am trying to run the demo 'pipelineMain.m', and I get an error:
`Function or variable 'initOutDir' is not recognized.`
Where am I going wrong here? I did not find any function named 'initOutDir' in the file 'pipelineMain.m'

**Comment by Fmijsters** [comment]
Hey, I have the same problem have you managed to fix it?

**Comment by bmaneesh** [comment]
Hi @JasonAnn @Fmijsters, thanks for bringing the issue to our notice. Can you try the mesh_visualization branch? It does not have the `initOutDir` issue. We added some visualization based flags(see the readme on the same branch) to save/render mesh overlays. 

I have not tested InfantAFAR but if you have this issue, a copy of `initOutDir` from `mfile` on mesh_visualization branch should work. We will evaluate any conflicts with master and merge the changes.

Please let us know if you are having any further issues. We will also be releasing a faster and more user-friendly version soon. So please stay tuned.

**Comment by Fmijsters** [comment]
@bmaneesh Thank you for your response. Sadly I still can't seem to run the mesh_visualisation branch. Could you provide some basic instructions on how to run it from a fresh clone?

**Comment by bmaneesh** [comment]
After you clone from the mesh_visualization branch, you will need to follow the instructions in the README on the [branch](https://github.com/AffectAnalysisGroup/AFARtoolbox/tree/mesh_visualization). Though it does not change the installation instructions wrt the main branch. If you have any errors installing, can you post them?

**Comment by Fmijsters** [comment]
I added the opencv directory (opencv_2.4.11_x64_vc11_dlls) to the system environment variables but it still throws this error: "Unable to resolve the name 'cv.CascadeClassifier'. When running the Demo_Video.m file

Error in CZFace/LoadFromFile"

**Comment by bmaneesh** [comment]
Can you try [this code](https://github.com/AffectAnalysisGroup/AFARtoolbox/blob/mesh_visualization/test_functions/test_zface.m) instead of Demo_Video.m? If you still get this error, I believe it could be because of some path issue. So please check if the models [here](https://github.com/AffectAnalysisGroup/AFARtoolbox/tree/master/zface/ZFace_models) and [here](https://github.com/AffectAnalysisGroup/AFARtoolbox/tree/master/zface/haarcascade_frontalface_alt2.xml) exist on your local.

Depending on your OS, the backward slash(`\`) in the path might not work. So please change it accordingly in the file path. 

Could you confirm if you also have the mexopencv installed and working as mentioned [here](https://github.com/kyamagu/mexopencv)?
